name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@10e2db214292b813e594b1bd820017798e3df0bf # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install
          
        - name: SonarQube Scan
            uses: SonarSource/sonoarqube-scan-action@10e2db214292b813e594b1bd820017798e3df0bf # v6.0.0
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     